##                                              CLEAN THE DATASET

## Importing Libraries

In [11]:
import pandas as pd
import numpy as np
from collections import Counter as c
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
import pickle

## Reading the dataset

In [12]:
# Loading the dataset
data = pd.read_csv("4.chronickidneydisease.csv")

In [13]:
data.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd

In [14]:
data.tail()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [15]:
data.drop(["id"], axis = 1, inplace = True)

In [16]:
data.columns

Index(['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu',
       'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [17]:
data.columns = ['age', 'blood_pressure', 'specific_gravity', 'albumin', 'sugar', 'red_blood_cells', 'pus_cell', 
                'pus_cell_clumps', 'bacteria', 'blood glucose random', 'blood_urea', 'serum_creatinine', 'sodium', 'potassium',
                'hemoglobin', 'packed_cell_volume', 'white_blood_cell_count', 'red_blood_cell_count', 'hypertension', 
                'diabetesmellitus', 'coronary_artery_disease', 'appetite', 'pedal_edema', 'anemia', 'class']
data.columns

Index(['age', 'blood_pressure', 'specific_gravity', 'albumin', 'sugar',
       'red_blood_cells', 'pus_cell', 'pus_cell_clumps', 'bacteria',
       'blood glucose random', 'blood_urea', 'serum_creatinine', 'sodium',
       'potassium', 'hemoglobin', 'packed_cell_volume',
       'white_blood_cell_count', 'red_blood_cell_count', 'hypertension',
       'diabetesmellitus', 'coronary_artery_disease', 'appetite',
       'pedal_edema', 'anemia', 'class'],
      dtype='object')

In [18]:
data.head()

,age,blood_pressure,specific_gravity,albumin,sugar,red_blood_cells,pus_cell,pus_cell_clumps,bacteria,blood glucose random,...,packed_cell_volume,white_blood_cell_count,red_blood_cell_count,hypertension,diabetesmellitus,coronary_artery_disease,appetite,pedal_edema,anemia,class
0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,...,35,7300,4.6,no,no,no,good,no,no,ckd

## Understanding data type and summary of features

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      391 non-null    float64
 1   blood_pressure           388 non-null    float64
 2   specific_gravity         353 non-null    float64
 3   albumin                  354 non-null    float64
 4   sugar                    351 non-null    float64
 5   red_blood_cells          248 non-null    object
 6   pus_cell                 335 non-null    object
 7   pus_cell_clumps          396 non-null    object
 8   bacteria                 396 non-null    object
 9   blood glucose random     356 non-null    float64
 10  blood_urea               381 non-null    float64
 11  serum_creatinine         383 non-null    float64
 12  sodium                   313 non-null    float64
 13  potassium                312 non-null    float64
 14  hemoglobin               348 non-null    float64
 15  packed_cell_volume       330 non-null    object
 16  white_blood_cell_count   295 non-null    object
 17  red_blood_cell_count     270 non-null    object
 18  hypertension             398 non-null    object
 19  diabetesmellitus         398 non-null    object
 20  coronary_artery_disease  398 non-null    object
 21  appetite                 399 non-null    object
 22  pedal_edema              399 non-null    object
 23  anemia                   399 non-null    object
 24  class                    400 non-null    object
dtypes: float64(11), object(14)
memory usage: 78.2+ KB

Target Column

In [20]:
data['class'].unique()

array(['ckd', 'ckd\t', 'notckd'], dtype=object)

Rectifying the target column

In [21]:
data['class'] = data['class'].replace("ckd\t", "ckd")
data['class'].unique()

array(['ckd', 'notckd'], dtype=object)

-----

Categorical columns

In [22]:
catcols = set(data.dtypes[data.dtypes == 'O'].index.values)
print(catcols)

{'bacteria', 'pus_cell_clumps', 'anemia', 'coronary_artery_disease', 'pedal_edema', 'packed_cell_volume', 'red_blood_cells', 'class', 'pus_cell', 'hypertension', 'appetite', 'red_blood_cell_count', 'diabetesmellitus', 'white_blood_cell_count'}

Removing columns that are not categorical

In [23]:
catcols.remove('red_blood_cell_count')
catcols.remove('packed_cell_volume')
catcols.remove('white_blood_cell_count')
print(catcols)

{'bacteria', 'pus_cell_clumps', 'anemia', 'coronary_artery_disease', 'pedal_edema', 'red_blood_cells', 'class', 'pus_cell', 'hypertension', 'appetite', 'diabetesmellitus'}

-----

Numerical Columns

In [24]:
contcols = set(data.dtypes[data.dtypes != 'O'].index.values)
print(contcols)

{'blood_urea', 'specific_gravity', 'sodium', 'albumin', 'hemoglobin', 'blood glucose random', 'serum_creatinine', 'age', 'blood_pressure', 'potassium', 'sugar'}

Remove columns that are not numerical

In [25]:
contcols.remove('specific_gravity')
contcols.remove('albumin')
contcols.remove('sugar')
print(contcols)

{'blood_urea', 'sodium', 'hemoglobin', 'blood glucose random', 'serum_creatinine', 'age', 'blood_pressure', 'potassium'}

--------

Adding columns to numerical that were found continous in categorical analysis

In [26]:
contcols.add('red_blood_cell_count')
contcols.add('packed_cell_volume')
contcols.add('white_blood_cell_count')
print(contcols)

{'blood_urea', 'sodium', 'packed_cell_volume', 'hemoglobin', 'blood glucose random', 'serum_creatinine', 'age', 'blood_pressure', 'red_blood_cell_count', 'potassium', 'white_blood_cell_count'}

------------

Adding columns to categorical that were found in numerical analysis

In [27]:
catcols.add('specific_gravity')
catcols.add('albumin')
catcols.add('sugar')
print(catcols)

{'bacteria', 'pus_cell_clumps', 'specific_gravity', 'anemia', 'coronary_artery_disease', 'pedal_edema', 'albumin', 'red_blood_cells', 'class', 'pus_cell', 'hypertension', 'appetite', 'diabetesmellitus', 'sugar'}

-------------------

Replace unnecessary values in categorical columns

In [28]:
data['coronary_artery_disease'] = data.coronary_artery_disease.replace('\tno', 'no')
c(data['coronary_artery_disease'])

Counter({'no': 364, 'yes': 34, nan: 2})

In [29]:
data['diabetesmellitus'] = data.diabetesmellitus.replace(to_replace = {'\tno': 'no', '\tyes' : 'yes', ' yes' : 'yes'})
c(data['diabetesmellitus'])

Counter({'yes': 137, 'no': 261, nan: 2})

## Handling missing values

Checking for missing values

In [30]:
data.isnull().any()

age                         True
blood_pressure              True
specific_gravity            True
albumin                     True
sugar                       True
red_blood_cells             True
pus_cell                    True
pus_cell_clumps             True
bacteria                    True
blood glucose random        True
blood_urea                  True
serum_creatinine            True
sodium                      True
potassium                   True
hemoglobin                  True
packed_cell_volume          True
white_blood_cell_count      True
red_blood_cell_count        True
hypertension                True
diabetesmellitus            True
coronary_artery_disease     True
appetite                    True
pedal_edema                 True
anemia                      True
class                      False
dtype: bool

In [31]:
data.isnull().sum()

age                          9
blood_pressure              12
specific_gravity            47
albumin                     46
sugar                       49
red_blood_cells            152
pus_cell                    65
pus_cell_clumps              4
bacteria                     4
blood glucose random        44
blood_urea                  19
serum_creatinine            17
sodium                      87
potassium                   88
hemoglobin                  52
packed_cell_volume          70
white_blood_cell_count     105
red_blood_cell_count       130
hypertension                 2
diabetesmellitus             2
coronary_artery_disease      2
appetite                     1
pedal_edema                  1
anemia                       1
class                        0
dtype: int64

------------------

Convet the string format to numeric in numerical data

In [32]:
data.packed_cell_volume = pd.to_numeric(data.packed_cell_volume, errors = 'coerce')
data.white_blood_cell_count = pd.to_numeric(data.white_blood_cell_count, errors = 'coerce')
data.red_blood_cell_count = pd.to_numeric(data.red_blood_cell_count, errors = 'coerce')

---

Replace missing values

In [33]:
# Numerical

data['blood glucose random'].fillna(data['blood glucose random'].mean(), inplace = True)
data['blood_pressure'].fillna(data['blood_pressure'].mean(), inplace = True)
data['blood_urea'].fillna(data['blood_urea'].mean(), inplace = True)
data['hemoglobin'].fillna(data['hemoglobin'].mean(), inplace = True)
data['packed_cell_volume'].fillna(data['packed_cell_volume'].mean(), inplace = True)
data['potassium'].fillna(data['potassium'].mean(), inplace = True)
data['red_blood_cell_count'].fillna(data['red_blood_cell_count'].mean(), inplace = True)
data['serum_creatinine'].fillna(data['serum_creatinine'].mean(), inplace = True)
data['sodium'].fillna(data['sodium'].mean(), inplace = True)
data['white_blood_cell_count'].fillna(data['white_blood_cell_count'].mean(), inplace = True)

In [34]:
# Categorical

data['age'].fillna(data['age'].mode()[0], inplace = True)
data['hypertension'].fillna(data['hypertension'].mode()[0], inplace = True)
data['pus_cell_clumps'].fillna(data['pus_cell_clumps'].mode()[0], inplace = True)
data['appetite'].fillna(data['appetite'].mode()[0], inplace = True)
data['albumin'].fillna(data['albumin'].mode()[0], inplace = True)
data['pus_cell'].fillna(data['pus_cell'].mode()[0], inplace = True)
data['red_blood_cells'].fillna(data['red_blood_cells'].mode()[0], inplace = True)
data['coronary_artery_disease'].fillna(data['coronary_artery_disease'].mode()[0], inplace = True)
data['bacteria'].fillna(data['bacteria'].mode()[0], inplace = True)
data['anemia'].fillna(data['anemia'].mode()[0], inplace = True)
data['sugar'].fillna(data['sugar'].mode()[0], inplace = True)
data['diabetesmellitus'].fillna(data['diabetesmellitus'].mode()[0], inplace = True)
data['pedal_edema'].fillna(data['pedal_edema'].mode()[0], inplace = True)
data['specific_gravity'].fillna(data['specific_gravity'].mode()[0], inplace = True)

In [35]:
data.isnull().sum()

age                        0
blood_pressure             0
specific_gravity           0
albumin                    0
sugar                      0
red_blood_cells            0
pus_cell                   0
pus_cell_clumps            0
bacteria                   0
blood glucose random       0
blood_urea                 0
serum_creatinine           0
sodium                     0
potassium                  0
hemoglobin                 0
packed_cell_volume         0
white_blood_cell_count     0
red_blood_cell_count       0
hypertension               0
diabetesmellitus           0
coronary_artery_disease    0
appetite                   0
pedal_edema                0
anemia                     0
class                      0
dtype: int64

## Label Encoding

In [36]:
for i in catcols:
    print("Label Encoding of : ", i)
    LEi = LabelEncoder()
    print(c(data[i]))
    data[i] = LEi.fit_transform(data[i])
    print(c(data[i]))
    print("*"*100)

Label Encoding of :  bacteria
Counter({'notpresent': 378, 'present': 22})
Counter({0: 378, 1: 22})
****************************************************************************************************
Label Encoding of :  pus_cell_clumps
Counter({'notpresent': 358, 'present': 42})
Counter({0: 358, 1: 42})
****************************************************************************************************
Label Encoding of :  specific_gravity
Counter({1.02: 153, 1.01: 84, 1.025: 81, 1.015: 75, 1.005: 7})
Counter({3: 153, 1: 84, 4: 81, 2: 75, 0: 7})
****************************************************************************************************
Label Encoding of :  anemia
Counter({'no': 340, 'yes': 60})
Counter({0: 340, 1: 60})
****************************************************************************************************
Label Encoding of :  coronary_artery_disease
Counter({'no': 366, 'yes': 34})
Counter({0: 366, 1: 34})
****************************************************************************************************
Label Encoding of :  pedal_edema
Counter({'no': 324, 'yes': 76})
Counter({0: 324, 1: 76})
****************************************************************************************************
Label Encoding of :  albumin
Counter({0.0: 245, 1.0: 44, 2.0: 43, 3.0: 43, 4.0: 24, 5.0: 1})
Counter({0: 245, 1: 44, 2: 43, 3: 43, 4: 24, 5: 1})
****************************************************************************************************
Label Encoding of :  red_blood_cells
Counter({'normal': 353, 'abnormal': 47})
Counter({1: 353, 0: 47})
****************************************************************************************************
Label Encoding of :  class
Counter({'ckd': 250, 'notckd': 150})
Counter({0: 250, 1: 150})
****************************************************************************************************
Label Encoding of :  pus_cell
Counter({'normal': 324, 'abnormal': 76})
Counter({1: 324, 0: 76})
****************************************************************************************************
Label Encoding of :  hypertension
Counter({'no': 253, 'yes': 147})
Counter({0: 253, 1: 147})
****************************************************************************************************
Label Encoding of :  appetite
Counter({'good': 318, 'poor': 82})
Counter({0: 318, 1: 82})
****************************************************************************************************
Label Encoding of :  diabetesmellitus
Counter({'no': 263, 'yes': 137})
Counter({0: 263, 1: 137})
****************************************************************************************************
Label Encoding of :  sugar
Counter({0.0: 339, 2.0: 18, 3.0: 14, 4.0: 13, 1.0: 13, 5.0: 3})
Counter({0: 339, 2: 18, 3: 14, 4: 13, 1: 13, 5: 3})
****************************************************************************************************

**Split the data set into dependent and independent variable**

In [37]:
selcols=['red_blood_cells','pus_cell','blood glucose random','blood_urea','pedal_edema','anemia','diabetesmellitus','coronary_artery_disease']
x=pd.DataFrame(data,columns=selcols)
y=pd.DataFrame(data,columns=['class'])
print(x.shape)
print(y.shape)

(400, 8)
(400, 1)

**split the dataset into train set and test set**

In [38]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(320, 8)
(320, 1)
(80, 8)
(80, 1)

**Model building**

In [39]:
lgr=LogisticRegression()
lgr.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

LogisticRegression()

**Test the model**

In [40]:
y_pred=lgr.predict(x_test)
y_pred1=lgr.predict([[129,99,1,0,0,1,0,1]])
print(y_pred)
c(y_pred)

[0 0 0 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1 1 0 1 1 0 1 0 1 0 0 1 0 0 1 0 0 0 0 1
 0 0 1 0 1 0 0 0 1 0 1 1 1 0 0 0 1 0 1 0 1 1 0 0 1 1 0 0 0 0 1 0 1 1 0 0 1
 0 1 0 1 1 0]

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  "X does not have valid feature names, but"

Counter({0: 48, 1: 32})

In [41]:
accuracy_score(y_test,y_pred)

0.925

In [42]:
conf_mat=confusion_matrix(y_test,y_pred)
conf_mat

array([[48,  6],
       [ 0, 26]])

In [43]:
pickle.dump(lgr,open('CKD.pkl','wb'))