# HARSHINI P - 917719C034

# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
s.split()

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [4]:
print("The diameter of {} is {} kilometers.".format(planet, diameter))

The diameter of Earth is 12742 kilometers.

## 3. In this nest dictionary grab the word "hello"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [7]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [8]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [10]:
arr = np.arange(20,35,2)
arr

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
mat = np.arange(0, 9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a, b), axis = 0)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [13]:
import pandas as pd

In [14]:
A = np.random.randint(10, size=(3,2))
df = pd.DataFrame(A)
df

   0  1
0  4  3
1  0  1
2  3  9

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [15]:
import datetime

date = datetime.datetime.strptime("01-01-2023", "%d-%m-%Y")
date_generated = pd.date_range(date, periods=41)

print(date_generated.strftime("%d-%m-%Y"))

Index(['01-01-2023', '02-01-2023', '03-01-2023', '04-01-2023', '05-01-2023',
       '06-01-2023', '07-01-2023', '08-01-2023', '09-01-2023', '10-01-2023',
       '11-01-2023', '12-01-2023', '13-01-2023', '14-01-2023', '15-01-2023',
       '16-01-2023', '17-01-2023', '18-01-2023', '19-01-2023', '20-01-2023',
       '21-01-2023', '22-01-2023', '23-01-2023', '24-01-2023', '25-01-2023',
       '26-01-2023', '27-01-2023', '28-01-2023', '29-01-2023', '30-01-2023',
       '31-01-2023', '01-02-2023', '02-02-2023', '03-02-2023', '04-02-2023',
       '05-02-2023', '06-02-2023', '07-02-2023', '08-02-2023', '09-02-2023',
       '10-02-2023'],
      dtype='object')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [16]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [17]:
df = pd.DataFrame(lists)
df

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24